---
title: "gam"
author: "Gianmarco"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## General Additive Model (GAM)

Now we try to use the GAM model to analyze the possibility of non-linear relationships between the features.

```{r}
library(mgcv)
#we fit the GAM model on the different datasets
#On d_train
gam_train = gam( quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(density) + s(pH) + s(sulphates) + s(alcohol), data = d_train, family = gaussian(link = "identity")) 

summary(gam_train)
plot(gam_train)
print(gam_train$aic)


#On d_train_clean
gam_clean = gam( quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(density) + s(pH) + s(sulphates) + s(alcohol), data = d_train_clean, family = gaussian(link = "identity")) 

summary(gam_clean)
plot(gam_clean)
print(gam_clean$aic)


#On d_train_light
gam_light = gam( quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(pH) + s(sulphates) + s(alcohol), data = d_train_light, family = gaussian(link = "identity")) 

summary(gam_light)
plot(gam_light)
print(gam_light$aic)


#On d_train_light_clean
gam_light_clean = gam( quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(pH) + s(sulphates) + s(alcohol), data = d_train_light_clean, family = gaussian(link = "identity")) 

summary(gam_light_clean)
plot(gam_light_clean)
print(gam_light_clean$aic)
```

Now we consider the different values of the smoothing parameters in the GAM and how we could improve them. We do this by checking if for each feature it would be better to use the already found smoothing parameter or its double.
```{r}
#For d_train
sp1_train = gam_train$sp
sp2_train = 2 * sp1_train
t = rbind(sp1_train,sp2_train) #creates a matrix with sp1 and sp2 as rows

sp.grid = expand.grid(t[,1], t[,2], t[,3], t[,4], t[,5], t[,6], t[,7], t[,8], t[,9], t[,10], t[,11]) # creates a dataframe whose rows are the different possible combinations of smoothing parameters
n.tuning = nrow(sp.grid)
#Now I create the vector of the different AIC for each combination of values
aic = rep(NA, n.tuning)
#And now I perform the grid search
for(i in 1:n.tuning){
 gamobj = gam(quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(density) + s(pH) + s(sulphates) + s(alcohol), data = d_train, family = gaussian(link = "identity"), sp = sp.grid[i,]) 
 aic[i] = AIC(gamobj)
 
}
# Find the minimum
opt.sp_train = sp.grid[which.min(aic),]
print(opt.sp_train) 
```

```{r}
#For d_train_clean
sp1_clean = gam_clean$sp
sp2_clean = 2 * sp1_clean
t = rbind(sp1_clean,sp2_clean) #creates a matrix with sp1 and sp2 as rows

sp.grid = expand.grid(t[,1], t[,2], t[,3], t[,4], t[,5], t[,6], t[,7], t[,8], t[,9], t[,10], t[,11]) # creates a dataframe whose rows are the different possible combinations of smoothing parameters
n.tuning = nrow(sp.grid)
#Now I create the vector of the different AIC for each combination of values
aic = rep(NA, n.tuning)
#And now I perform the grid search
for(i in 1:n.tuning){
 gamobj = gam(quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(density) + s(pH) + s(sulphates) + s(alcohol), data = d_train_clean, family = gaussian(link = "identity"), sp = sp.grid[i,]) 
 aic[i] = AIC(gamobj)
 
}
# Find the minimum
opt.sp_clean = sp.grid[which.min(aic),]
print(opt.sp_clean) 
```

```{r}
#For d_light
sp1_light = gam_light$sp
sp2_light = 2 * sp1_light
t = rbind(sp1_light,sp2_light) #creates a matrix with sp1 and sp2 as rows

sp.grid = expand.grid(t[,1], t[,2], t[,3], t[,4], t[,5], t[,6], t[,7], t[,8], t[,9], t[,10], t[,11]) # creates a dataframe whose rows are the different possible combinations of smoothing parameters
n.tuning = nrow(sp.grid)
#Now I create the vector of the different AIC for each combination of values
aic = rep(NA, n.tuning)
#And now I perform the grid search
for(i in 1:n.tuning){
 gamobj = gam(quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(pH) + s(sulphates) + s(alcohol), data = d_train_light, family = gaussian(link = "identity"), sp = sp.grid[i,]) 
 aic[i] = AIC(gamobj)
 
}
# Find the minimum
opt.sp_light = sp.grid[which.min(aic),]
print(opt.sp_light) 
```

```{r}
#For d_light_clean
sp1_light_clean = gam_light_clean$sp
sp2_light_clean = 2 * sp1_light_clean
t = rbind(sp1_light_clean,sp2_light_clean) #creates a matrix with sp1 and sp2 as rows

sp.grid = expand.grid(t[,1], t[,2], t[,3], t[,4], t[,5], t[,6], t[,7], t[,8], t[,9], t[,10], t[,11]) # creates a dataframe whose rows are the different possible combinations of smoothing parameters
n.tuning = nrow(sp.grid)
#Now I create the vector of the different AIC for each combination of values
aic = rep(NA, n.tuning)
#And now I perform the grid search
for(i in 1:n.tuning){
 gamobj = gam(quality ~ s(fixed.acidity) + s(volatile.acidity) + s(citric.acid) + s(residual.sugar) + s(chlorides) + s(total.sulfur.dioxide) + s(free.sulfur.dioxide) + s(pH) + s(sulphates) + s(alcohol), data = d_light_clean, family = gaussian(link = "identity"), sp = sp.grid[i,]) 
 aic[i] = AIC(gamobj)
 
}
# Find the minimum
opt.sp_light_clean = sp.grid[which.min(aic),]
print(opt.sp_light_clean) 
```